name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalando clj-kondo
        run: |
          curl -sLO https://github.com/clj-kondo/clj-kondo/releases/latest/download/clj-kondo-linux-amd64.zip
          unzip clj-kondo-linux-amd64.zip
          sudo mv clj-kondo /usr/local/bin/

      - name: Analisis estatico
        run: clj-kondo --lint src
